/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uoc.tds.pec3.client;

import java.awt.BorderLayout;
import java.awt.FlowLayout;

import edu.uoc.tds.pec3.common.GestorEstocInterface;
import edu.uoc.tds.pec3.i18n.TDSLanguageUtils;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;

/**
 *
 * @author C005352
 */
public class ClienteMenu extends javax.swing.JFrame {

    private GestorEstocInterface remoto;
    private final String URL = "localhost";
    private final int PORT = 1099;
    private final String JNDI_NAME = "GestorEstoc";
    

    
    
     
    
    /**
     * Creates new form ClienteMenu
     */
    public ClienteMenu() {
        initComponents();
         this.setLayout(new FlowLayout());
        TDSLanguageUtils.setDefaultLanguage("i18n/messages");
        this.setTitle(TDSLanguageUtils.getMessage("Application.title"));
        jLbTitle.setText(TDSLanguageUtils.getMessage("Application.title"));
        jMenuFile.setText(TDSLanguageUtils.getMessage("Cliente.menuFile.text"));
        jMenuOptions.setText(TDSLanguageUtils.getMessage("Cliente.menuOptions.text"));
        jMenuItem2.setText(TDSLanguageUtils.getMessage("Cliente.menuItem1_2.text"));
        jMenuItem1.setText(TDSLanguageUtils.getMessage("Cliente.menuItem1_1.text"));
        jMenuItem4.setText(TDSLanguageUtils.getMessage("Cliente.menuItem2_1.text"));
        jMenuItem5.setText(TDSLanguageUtils.getMessage("Cliente.menuItem2_2.text"));
        jMenuItem6.setText(TDSLanguageUtils.getMessage("Cliente.menuItem2_3.text"));
    }

          private Alta_PeticionUI AP;
          private Atender_PeticionUI AT;
          private Entrada_StockUI ES;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbTitle = new javax.swing.JLabel();
        jMenuBar14 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuOptions = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        getContentPane().setLayout(null);

        jLbTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLbTitle.setForeground(new java.awt.Color(0, 51, 153));
        jLbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbTitle.setText("jLabel1");
        getContentPane().add(jLbTitle);
        jLbTitle.setBounds(110, 70, 218, 32);

        jMenuFile.setText("File");

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem2);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItem1);

        jMenuBar14.add(jMenuFile);

        jMenuOptions.setText("Edit");

        jMenuItem4.setText("jMenuItem4");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuItem5);

        jMenuItem6.setText("jMenuItem6");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuItem6);

        jMenuBar14.add(jMenuOptions);

        setJMenuBar(jMenuBar14);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-535)/2, (screenSize.height-218)/2, 535, 218);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        //Iniciar conexion con el seridor
        conectarCliente();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        //Salir
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        	
		//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(ES);
			}
			catch(Exception e){
			}
			
			
		//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(AT);
			}
			catch(Exception e){
			}	
			//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(AP);
			}
			catch(Exception e){
			}		
                        
                        
                        
                   jLbTitle.setVisible(false);
                   
                        
                        
                        
   //Creamos una nueva instancia de 		
        AP = new Alta_PeticionUI();

        //Agregamos la instancia al JFrame, con un layout al centro
        this.add(AP, BorderLayout.CENTER);

        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();// TODO add your handling code here:    


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
		
		//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(ES);
			}
			catch(Exception e){
			}
			
			
		//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(AT);
			}
			catch(Exception e){
			}	
			//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(AP);
			}
			catch(Exception e){
			}	
		
		
	jLbTitle.setVisible(false);	
        
        ES = new Entrada_StockUI();

        //Agregamos la instancia al JFrame, con un layout al centro
        this.add(ES, BorderLayout.CENTER);

        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();// TODO add your handling code here:    
           
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
		//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(ES);
			}
			catch(Exception e){
			}
			
			
		//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(AT);
			}
			catch(Exception e){
			}	
			//Si ya está el otro Jpanel añadido al contenedor, entonces se elimina
			try{
			this.remove(AP);
			}
			catch(Exception e){
			}	  
        
        		     //Creamos una nueva instancia de
       jLbTitle.setVisible(false);
                        
        AT = new Atender_PeticionUI();

        //Agregamos la instancia al JFrame, con un layout al centro
        this.add(AT, BorderLayout.CENTER);

        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();// TODO add your handling code here:  
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange



    public void conectarCliente() {
        try {
            System.out.println("Conectando al servidor desde cliente...");
            Registry registry = LocateRegistry.getRegistry(URL, PORT);
            remoto = (GestorEstocInterface) registry.lookup(JNDI_NAME);
            JOptionPane.showMessageDialog(this, TDSLanguageUtils.getMessage("Cliente.mensajeConectadoServidor"));
        } catch (NotBoundException e) {            
            JOptionPane.showMessageDialog(this, TDSLanguageUtils.getMessage("RMI.conexion.error"));
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(this, TDSLanguageUtils.getMessage("RMI.conexion.error_remoto"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
        
    private void realizarTest() {
        System.out.println("Realizando test...");
        try {
            String respuesta = remoto.test();
            JOptionPane.showMessageDialog(this, respuesta);
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbTitle;
    private javax.swing.JMenuBar jMenuBar14;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuOptions;
    // End of variables declaration//GEN-END:variables
}
