/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uoc.tds.pec3.server;

import edu.uoc.tds.pec3.beans.Recurso;
import edu.uoc.tds.pec3.common.GestorEstocInterface;
import edu.uoc.tds.pec3.i18n.TDSLanguageUtils;
import edu.uoc.tds.pec3.server.impl.GestorEstocInterfaceImpl;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class ServidorOnOff extends javax.swing.JFrame {

    private final int PORT = 1099;
    private final String JNDI_NAME = "GestorEstoc";
    private Registry registry;
    
    /**
     * Creates new form ServidorOnOff
     */
    public ServidorOnOff() {
        initComponents();
        TDSLanguageUtils.setDefaultLanguage("i18n/messages");
        this.setTitle(TDSLanguageUtils.getMessage("Application.title"));
        jLbMsg.setText(TDSLanguageUtils.getMessage("ServidorOnOf.mensajeServidorNoIniciado.text"));
        jButton1.setText(TDSLanguageUtils.getMessage("ServidorOnOf.btnIniciarServidor.text"));
        jButton2.setText(TDSLanguageUtils.getMessage("ServidorOnOf.btnDetenerServidor.text"));
        jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLbMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLbMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLbMsg.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		try {
			jLbMsg.setText(TDSLanguageUtils.getMessage("ServidorOnOf.mensajeServidorIniciando.text"));
			registry = LocateRegistry.createRegistry(PORT);	
                        GestorEstocInterface objetoRemoto = new GestorEstocInterfaceImpl();
                        Test(objetoRemoto);
			registry.rebind(JNDI_NAME, objetoRemoto);
			jLbMsg.setText(TDSLanguageUtils.getMessage("ServidorOnOf.mensajeServidorIniciado.text"));
                        jButton1.setEnabled(false);
                        jButton2.setEnabled(true);
			
		} catch (RemoteException e) {		
			e.printStackTrace();
                        JOptionPane.showMessageDialog(this, e.getMessage());
			
		} catch (Exception e){
			e.printStackTrace();
                        JOptionPane.showMessageDialog(this, e.getMessage());
			
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Test(GestorEstocInterface objetoRemoto) throws RemoteException{
                                
        List<Recurso> recursos = objetoRemoto.obtenerRecursos();
        
        Recurso modificado=recursos.get(0);
        modificado.setStock(recursos.get(0).getStock()+1);
        JOptionPane.showMessageDialog(this, recursos.get(0).getStock());
        recursos.get(0).setStock(recursos.get(0).getStock()+1);
        JOptionPane.showMessageDialog(this, recursos.get(0).getStock());
        objetoRemoto.altaRecurso(recursos.get(0));
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            registry.unbind(JNDI_NAME); 
            registry = null;
            jLbMsg.setText(TDSLanguageUtils.getMessage("ServidorOnOf.mensajeServidorNoIniciado.text"));
        } catch (RemoteException ex) {
            Logger.getLogger(ServidorOnOff.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(ServidorOnOff.class.getName()).log(Level.SEVERE, null, ex);
        } 
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorOnOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorOnOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorOnOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorOnOff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                     
                
                new ServidorOnOff().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLbMsg;
    // End of variables declaration//GEN-END:variables



}
